// packages/common-docs/react-demo/Button.tsx
import React from 'react';
import './button.css';

interface ButtonProps {
    /**
     * Is this the principal call to action on the page?
     */
    primary?: boolean;
    /**
     * What background color to use
     */
    backgroundColor?: string;
    /**
     * How large should the button be?
     */
    size?: 'small' | 'medium' | 'large';
    /**
     * Button contents
     */
    label: string;
    /**
     * Optional click handler
     */
    onClick?: () => void;
}

/**
 * Primary UI component for user interaction
 */
export const Button = ({primary = false, size = 'medium', backgroundColor, label, ...props}: ButtonProps) => {
    const mode = primary ? 'storybook-button--primary' : 'storybook-button--secondary';
    return (
        <button
            type="button"
            className={['storybook-button', `storybook-button--${size}`, mode].join(' ')}
            style={{backgroundColor}}
            {...props}
        >
            {label}
        </button>
    );
};

// packages/common-docs/vue-demo/Button.vue
<template>
    <button type="button" :class="classes" @click="onClick" :style="style">
        {{ label }}
    </button>
</template>

<script>
    import './button.css';

    export default {
        name: 'my-button',

        props: {
            label: {
                type: String,
                required: true,
            },
            primary: {
                type: Boolean,
                default: false,
            },
            size: {
                type: String,
                default: 'medium',
                validator: function (value) {
                    return ['small', 'medium', 'large'].indexOf(value) !== -1;
                },
            },
            backgroundColor: {
                type: String,
            },
        },

        computed: {
            classes () {
                return {
                    'storybook-button': true,
                    'storybook-button--primary': this.primary,
                    'storybook-button--secondary': !this.primary,
                    [`storybook-button--${this.size}`]: true,
                };
            },
            style () {
                return {
                    backgroundColor: this.backgroundColor,
                };
            },
        },

        methods: {
            onClick () {
                this.$emit('onClick');
            },
        },
    };
</script>
